### PR TITLE
 Remove Attribute Names to Identify Models in Refocus

### PR DESCRIPTION
**Pull request by tausifmuzaffar**
Remove Attribute Names to Identify Models in Refocus

### CODE REVIEW

**Comment by tausifmuzaffar** [comment]
After https://github.com/salesforce/refocus/pull/655 is merge this should be ready to merge

**Comment by tausifmuzaffar** [comment]
@iamigo I agree there will be manual testing done in devbox. What action items do you think this needs to get approved?

**Comment by iamigo** [comment]
You can deploy the branch to devbox before it is merged to master and test it there.

**Comment by tausifmuzaffar** [comment]
@iamigo @pallavi2209 I ran tests on the devbox seems to be working can i go ahead and merge this?

**Comment by pallavi2209** [comment]
Sounds good to me.

**Pull request merged**
