### PR TITLE
Blob UI API and Tests

### PR DESCRIPTION
**Pull request by tausifmuzaffar**
/bots add the UI column to API

### CODE REVIEW

**Comment by tausifmuzaffar** [comment]
@iamigo @shriramshankar "jobCleanup delay - staggered -  jobs: 20, delay: 159ms:" - test is failing

 Do you think something in my code is causing this?  Im not familiar with that code at all.

**Comment by iamigo** [comment]
@jgraff2

**Comment by jgraff2** [comment]
This is from my code that was merged earlier today.

I had some difficulty getting these to pass consistently since they rely on timing. There's a tradeoff between increasing the timeouts to make it pass more reliably and having the tests take too long. I thought I had figured it out, but I guess not.

I will increase the timeout for those tests to make it more reliable.

**Comment by iamigo** [comment]
2 bots tests failing now

**Comment by tausifmuzaffar** [comment]
There was a bad merge where the put got moved, an aspect test is failing now. is that a known issue?

**Pull request merged**
