### PR TITLE
Added useful links in the footer

### PR DESCRIPTION
**Pull request by kriscfoster**
screen shot 2018-09-14 at 10 40 40

screen shot 2018-09-14 at 10 40 48

**migrations/20180913102747-add-helpUrl-and-ownerUrl.js**
 - Migration to add docsUrl & helpUrl fields to Bots

**db/model/bot.js**
- Added docsUrl & helpUrl fields to DB (both validated with isUrl)

**api/v1/swagger.yaml**
- Added docsUrl & helpUrl to POST (not required), PATCH (not required), PUT (not required), GET Methods

**tests/db/model/bot/create.js**
**tests/api/v1/bots/get.js**
**tests/api/v1/bots/patch.js**
**tests/api/v1/bots/put.js**
**tests/api/v1/bots/post.js**
- Changed tests to include docsUrl & helpUrl

**view/rooms/utils/page.js**
- Added function to create a link element containing an svg image.

**tests/view/rooms/utils/page.js**
- Test for function which creates footer linked svgs

**view/rooms/app.js**
- Adds linked svgs to footer of bots if they have docsUrl or helpUrl
- Decrease footer size

### CODE REVIEW

**Comment by kriscfoster** [comment]
still some work to do here

**Comment by kriscfoster** [comment]
@iamigo This is true & I considered before making it, I can split up now if you think that would be better?

**Comment by iamigo** [comment]
@kriscfoster I'll review it as is, just guidance for the future - smaller PR is always better than bigger PR

**Comment by kriscfoster** [comment]
@iamigo Just after testing up and down in devbox-2 and everything looked good

**Comment by iamigo** [comment]
still waiting for @BrandonMurnane review?

**Pull request merged**
