### PR TITLE
Change Bot Data Values to Text

### PR DESCRIPTION
**Pull request by tausifmuzaffar**
Bot Data will be using very big values sometimes and so we need to make that column, because strings max at 255

### CODE REVIEW

**Comment by tausifmuzaffar** [comment]
@iamigo  tested it locally up and down. Do i do a manually release to devbox to test it? And the Payload limit is how we want to limit it

**Comment by iamigo** [comment]
Yes, manually deploy to devbox

**Comment by tausifmuzaffar** [comment]
@iamigo i have tested it on devbox

**Comment by tausifmuzaffar** [comment]
@kamilsmuga please can you look at this pr?

**Pull request merged**
