### PR TITLE
Remove sample store flag sample api

### PR DESCRIPTION
**Pull request by shriramshankar**
This PR removes the "samplesStore flag" just from the samples controller.   The first and the second commit are the only real changes, the rest are changes to the tests.

### CODE REVIEW

**Comment by shriramshankar** [comment]
@iamigo @jgraff2 Can you take a look at this PR? This along with #744 #745 needs to be merged for my next changes.

**Comment by shriramshankar** [comment]
I deployed this branch in dev-box and tested are the sample endpoints. They work as expected.

**Comment by jgraff2** [comment]
@shriramshankar failing tests after merge of my PUT aspects PR.

**Comment by shriramshankar** [comment]
@jgraff2 I skipped the failing tests for now in put and patch aspect files. It has already been taken care of in the next set of changes I am working on.

**Pull request merged**
