### PR TITLE
currentCollector field api changes for generator endpoints

### PR DESCRIPTION
**Pull request by pallavi2209**

### CODE REVIEW

**Comment by shriramshankar** [comment]
@iamigo, The "collector reassignment" spike that was done, assumes that a current collector has already been assigned by the user. If we want to make it read-only, we have also have to revert #823.

**Comment by pallavi2209** [comment]
I am holding off the changes until we decide.

**Comment by iamigo** [comment]
Refocus should set it to the first one in the list. I don’t think we want to let people do it--we should always be free to reassign as needed.

**Comment by pallavi2209** [comment]
Closing this Pr and creating a new one with reverted and new changes.

**Pull request closed without merging**
