### PR TITLE
Add remaining api logs

### PR DESCRIPTION
**Pull request by annyhe**

### CODE REVIEW

**Comment by annyhe** [comment]
Sorry for the messy commits. The changes are clean. Once this gets approved and merged all commits will be one commit.

**Comment by pallavi2209** [comment]
I think the PR includes the changes from previous commits as well. Can you please include the new changes only?

**Comment by annyhe** [comment]
@pallavi2209 Where do you see the old changes? I double checked the changes and they are the new ones.

**Comment by pallavi2209** [comment]
Sorry, nevermind, the number of commits and refactoring of code in similar files confused me.

**Pull request merged**
