### PR TITLE
in redis cache, on POST/PATCH/POST with field name, reject request

### PR DESCRIPTION
**Pull request by annyhe**
-tests only

### CODE REVIEW

**Comment by annyhe** [comment]
Good point. Changed base branch to reflect the dependency on #322

**Comment by iamigo** [comment]
@annyhe , "continuous-integration/travis-ci/push" had 3 tests failing, I just restarted that travis job to see if they'll pass.

**Comment by iamigo** [comment]
Nope, tests still failing @annyhe

**Comment by annyhe** [comment]
@iamigo The tests are expected to fail. Until the #320 is merged, there is no  checking of name in PUT, PATCH, and POST, so the tests that expect a 400 get a 201 status code.
Refer to https://github.com/salesforce/refocus/blob/cacheRejectSampleWithName/api/v1/helpers/nouns/samples.js
for the lack of 'name' field in the samples properties.

**Comment by pallavi2209** [comment]
@annyhe I am marking this DO NOT MERGE until #320 is merged.

**Pull request merged**
