### PR TITLE
fix docker-compose and use alpine linux

### PR DESCRIPTION
**Pull request by esemeniuc**
Features:
 - creates focusdb so database can be initialized (previously missing)
 - alpine cuts download size down to 1/5th of the old size
 - uses sem versioning to keep up with security patches
 - eliminates the finicky sleep env variable so node always starts after postgres is ready

### CODE REVIEW

**Comment by iamigo** [comment]
Thx for the contribution, @cwaffles! @dbabenko, does this look ok for you?

**Comment by dbabenko** [comment]
@iamigo the changes look great to me. I'm traveling right now outside of the country and cannot test the changes. Will be able to try them out closer to the end of the next week.

**Comment by Cwaffles** [comment]
Hi all,

could you please let me know why I was mentioned in this? 

Kind regards


Von meinem iPhone gesendet

**Comment by cassiodias** [comment]
@iamigo can we merge these changes, looks like it solves the current problem using Docker.

**Comment by iamigo** [comment]
approved but still requires CLA

**Comment by esemeniuc** [comment]
CLA signed. cwaffles was my old username (unrelated to the current user)

**Comment by esemeniuc** [comment]
Going to make a new pull request since the system is bugged

**Pull request closed without merging**
