### PR TITLE
remove PUT in sample generator template

### PR DESCRIPTION
**Pull request by annyhe**
- remove the PUT endpoint from generator template 
- no new code

### CODE REVIEW

**Comment by shriramshankar** [comment]
Need to remove the code in the controller too. Are we removing patch in the next PR?

**Comment by iamigo** [comment]
Patch is necessary but ONLY to update the isPublished field.

**Comment by annyhe** [comment]
The failing tests:  tests/api/v1/generators/getWithCollector.js  pass locally. I am re-running the tests on travis CI

**Comment by shriramshankar** [comment]
Ok to merge once tests pass.

**Pull request merged**
