### PR TITLE
Revert "Revert "add front end validation for tags (#114)" (#116)"

### PR DESCRIPTION
**Pull request by annyhe**
This reverts commit 0aa6a3ccac1b97ce0bda438d7b78968394faccdc.

### CODE REVIEW

**Comment by annyhe** [comment]
This works on staging. Try enter a tag with spaces: http://refocus-staging.herokuapp.com/subjects/SFDC-IT.SFM.Org62?edit

**Comment by annyhe** [comment]
@shriramshankar Please comment.

**Comment by shriramshankar** [comment]
Was trying to merge this and the commit message says "This reverts commit 0aa6a3ccac1b97ce0bda438d7b78968394faccdc." is that fine? @annyhe @iamigo

**Comment by annyhe** [comment]
@shriramshankar The commit message should be fine. Go ahead and merge.

**Pull request merged**
