### PR TITLE
testing event-flapper

### PR DESCRIPTION
**Pull request by BrandonMurnane**

### CODE REVIEW

**Comment by iamigo** [comment]
Perhaps getting closer, @BrandonMurnane -- looks like just this now...

  1) tests/api/v1/events/get.js > "before each" hook for "Pass, get array of multiple":
     TypeError: Cannot read property 'then' of undefined
      at Context.beforeEach (tests/api/v1/events/get.js:55:20)

**Comment by BrandonMurnane** [comment]
@iamigo is passing without any flappers re ran it a few times to be sure

**Comment by iamigo** [comment]
@BrandonMurnane looking good
I think you might need to rebase (?) this so that it only contains *your* changes (and not changes from other people's recent commits)

**Comment by BrandonMurnane** [comment]
@iamigo rebased

**Pull request merged**
