### PR TITLE
Get tags in admin working again

### PR DESCRIPTION
**Pull request by annyhe**

### CODE REVIEW

**Comment by annyhe** [comment]
@coveralls Is having some approximation issues: this pull request changed no existing tests; the coverage should stay the same.

**Comment by annyhe** [comment]
review app here http://refocus-pr-91.herokuapp.com/subjects/Salesforce.SFDC_Core.WAX.SPX.NA21?edit

**Comment by pallavi2209** [comment]
I checked for subjects and aspects tags - create/edit/delete. Works fine.

**Comment by annyhe** [comment]
@pallavi2209 @shriramshankar If no further comments or concerns, can we merge this now?

**Pull request merged**
