### PR TITLE
Adding new relic for lower level instrumentation.

### PR DESCRIPTION
**Pull request by iamigo**

### CODE REVIEW

**Comment by shriramshankar** [comment]
Need to provide a license too.

**Comment by iamigo** [comment]
> Need to provide a license too.

I thought that was done through heroku config, per https://docs.newrelic.com/docs/agents/nodejs-agent/hosting-services/nodejs-agent-heroku

**Comment by shriramshankar** [comment]
I was looking at the old refocus repo that had new relic setup. Harsh also had a newrelic.js file on the project root.
` ` `
/**
 * Copyright (c) 2016, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root or
 * https://opensource.org/licenses/BSD-3-Clause
 */

'use strict'

/**
 * New Relic agent configuration.
 *
 * See lib/config.defaults.js in the agent distribution for a more complete
 * description of configuration variables and their potential values.
 */
const conf = require('./config');

exports.config = {
  /**
   * Array of application names.
   */
  app_name: ['My Application'],
  /**
   * Your New Relic license key.
   */
  license_key: conf.newRelicKey,
  logging: {
    /**
     * Level at which to log. 'trace' is most useful to New Relic when diagnosing
     * issues with the agent, 'info' and higher will impose the least overhead on
     * production applications.
     */
    level: 'info'
  }
}
` ` `

**Comment by pallavi2209** [comment]
Restarted build to pass travis.

**Pull request merged**
