### PR TITLE
correct GET subjects/{key}/writers activity logging

### PR DESCRIPTION
**Pull request by shriramshankar**

### CODE REVIEW

**Comment by shriramshankar** [comment]
#309 and this one have the same root cause.

**Comment by harshkothari410** [comment]
any tests are there for this ? @shriramshankar

**Comment by shriramshankar** [comment]
Deployed this branch to staging. Check out http://refocus-staging.herokuapp.com/v1/subjects/Salesforce/writers

**Comment by shriramshankar** [comment]
@harshkothari410 @iamigo tests added.

**Pull request merged**
